<?php

namespace Proxies\__CG__\MyServiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisataeur extends \MyServiceBundle\Entity\Utilisataeur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'iduser', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'numero', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'nom', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'prenoms', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'idagence', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'idrole'];
        }

        return ['__isInitialized__', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'iduser', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'numero', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'nom', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'prenoms', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'idagence', '' . "\0" . 'MyServiceBundle\\Entity\\Utilisataeur' . "\0" . 'idrole'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisataeur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenoms($prenoms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenoms', [$prenoms]);

        return parent::setPrenoms($prenoms);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenoms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenoms', []);

        return parent::getPrenoms();
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduser();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', []);

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrole(\MyServiceBundle\Entity\Role $idrole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrole', [$idrole]);

        return parent::setIdrole($idrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrole', []);

        return parent::getIdrole();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdagence(\MyServiceBundle\Entity\Agence $idagence = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdagence', [$idagence]);

        return parent::setIdagence($idagence);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdagence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdagence', []);

        return parent::getIdagence();
    }

}
