<?php

namespace Proxies\__CG__\MyServiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Operationclassic extends \MyServiceBundle\Entity\Operationclassic implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperationclassic', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'commission', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'correspondant', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'position', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paysenvoi', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paysbeneficiaire', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'deviseenvoi', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'devisereception', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'pin', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'rate', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'action', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paiement', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'mode', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'pseudo', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperation', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idtypeoperation', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperateur'];
        }

        return ['__isInitialized__', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperationclassic', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'commission', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'correspondant', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'position', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paysenvoi', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paysbeneficiaire', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'deviseenvoi', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'devisereception', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'pin', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'rate', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'action', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'paiement', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'mode', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'pseudo', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperation', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idtypeoperation', '' . "\0" . 'MyServiceBundle\\Entity\\Operationclassic' . "\0" . 'idoperateur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Operationclassic $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdoperationclassic()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdoperationclassic();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperationclassic', []);

        return parent::getIdoperationclassic();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommission($commission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommission', [$commission]);

        return parent::setCommission($commission);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommission', []);

        return parent::getCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrespondant($correspondant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrespondant', [$correspondant]);

        return parent::setCorrespondant($correspondant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrespondant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrespondant', []);

        return parent::getCorrespondant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysenvoi($paysenvoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysenvoi', [$paysenvoi]);

        return parent::setPaysenvoi($paysenvoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysenvoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysenvoi', []);

        return parent::getPaysenvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysbeneficiaire($paysbeneficiaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysbeneficiaire', [$paysbeneficiaire]);

        return parent::setPaysbeneficiaire($paysbeneficiaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysbeneficiaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysbeneficiaire', []);

        return parent::getPaysbeneficiaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviseenvoi($deviseenvoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviseenvoi', [$deviseenvoi]);

        return parent::setDeviseenvoi($deviseenvoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviseenvoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviseenvoi', []);

        return parent::getDeviseenvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevisereception($devisereception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevisereception', [$devisereception]);

        return parent::setDevisereception($devisereception);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevisereception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevisereception', []);

        return parent::getDevisereception();
    }

    /**
     * {@inheritDoc}
     */
    public function setPin($pin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPin', [$pin]);

        return parent::setPin($pin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPin', []);

        return parent::getPin();
    }

    /**
     * {@inheritDoc}
     */
    public function setRate($rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRate', [$rate]);

        return parent::setRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRate', []);

        return parent::getRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement($paiement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', [$paiement]);

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', []);

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode($mode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', [$pseudo]);

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', []);

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperation(\MyServiceBundle\Entity\Operation $idoperation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperation', [$idoperation]);

        return parent::setIdoperation($idoperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperation', []);

        return parent::getIdoperation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtypeoperation(\MyServiceBundle\Entity\Typeoperation $idtypeoperation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtypeoperation', [$idtypeoperation]);

        return parent::setIdtypeoperation($idtypeoperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtypeoperation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtypeoperation', []);

        return parent::getIdtypeoperation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperateur(\MyServiceBundle\Entity\Ota $idoperateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperateur', [$idoperateur]);

        return parent::setIdoperateur($idoperateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperateur', []);

        return parent::getIdoperateur();
    }

}
